[theme]
base = "dark"
primaryColor = "#2A9D8F"
backgroundColor = "#000000"
secondaryBackgroundColor = "#151A16"
textColor = "#F2F5F2"
font = "sans serif"

[server]
headless = true
enableStaticServing = true
